### ISSUE TITLE
unable to backfill using upstox

### ISSUE THREAD

**Issue by prudhviRaj06** [Pritesh-Mhatre/autotrader#33]
504 Gateway Timeout
 JSON parse error: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null'); nested exception is com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null') at [Source: java.io.PushbackInputStream@15258a8; line: 1, column: 2]

these are the errors during the backfill.

**Comment by Pritesh-Mhatre** [comment]
Please provide the symbol for which this error occurred.

**Comment by Pritesh-Mhatre** [comment]
BANKNIFTY10JAN1927800CE: JSON parse error: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null'); nested exception is com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null') at [Source: java.io.PushbackInputStream@3d6f5a9b; line: 1, column: 2]

**Comment by prudhviRaj06** [comment]
Could not find matching instument, please make sure instruments are
downloaded from RTD screen & you have entered correct exchange & symbol.
504 Gateway Timeout
 JSON parse error: Unexpected character ('<' (code 60)): expected a valid
value (number, String, array, object, 'true', 'false' or 'null'); nested
exception is com.fasterxml.jackson.core.JsonParseException: Unexpected
character ('<' (code 60)): expected a valid value (number, String, array,
object, 'true', 'false' or 'null') at [Source:
java.io.PushbackInputStream@6274762d; line: 1, column: 2]


yes sir these are the three errors we get while backfilling from upstox
specially if we backfill pe orders sir, i thought problem is with my system
but got to know that everyone has the same problem.

**Comment by Pritesh-Mhatre** [comment]
Mostly this error seems to come for BANKNIFTY, will investigate it soon.
Symbol: **BANKNIFTY10JAN1927400PE**
Reporter: aniket011@gmail.com


Reporter: aniket011@gmail.com

**Comment by Pritesh-Mhatre** [comment]
**Issue has been fixed & will go live in 3.1.0 release. Closing this ticket.**
