### ISSUE TITLE
Overflow error & Make price rounding configurable

### ISSUE THREAD

**Issue by 9752354576** [Pritesh-Mhatre/autotrader#58]
Hello Auto Trader Support Team,

First  fall thank you very much for designing this software.
Today I have tested this software and i found bugs.

1) Problem Statement : 
We can not place order more then 32767 Quantity, if you will try to place order then you will get 'Run-time error '6' : Overflow'.

Solution :
Software should allows to place order for any number of quantity, this is required in real time trading.

2 While placing order, supposed you want to place order at 8.07 price but it will placed at 8.10 (divisible by 0.05)

Solution :
It should allow order at any price not should be divisible by 0.05, stock price divisible by 0.05 is not mandatory for all stocks this is required in real time trading.

not only other peoples also will faced this issue.

In case of any issue please reach me on my number 9752354576.

Thanks and Regards
Pankaj Kumar Solanki
Email : solanki.pankaj64@gmail.com
![auto trader error](https://user-images.githubusercontent.com/47362618/52291935-90f19f80-2999-11e9-9383-0dc6c3cefa80.JPG)

**Comment by Pritesh-Mhatre** [comment]
1. This will be investigated

2. This is a know feature added as many users were not aware of how to round the price. Most of the stocks & contracts have a tick size of 0.05; hence it was made default. Removing it will cause problem for 99.5% of the users; so we will make it configurable in future release. So that a user can disable it if needed (by default it will be enabled).

**Comment by Pritesh-Mhatre** [comment]
Order price rounding is made optional with a new setting **ROUND_ORDER_PRICE**.
It's default value will be set to **true** to avoid any impact to existing clients.
If you do not need price rounding, then set  **ROUND_ORDER_PRICE** to **false** in AutoTrader settings.

This change will go live in next release.

**Comment by Pritesh-Mhatre** [comment]
Excel issue has been fixed, the quantity data type changed to **Long**.
Earlier it was **Integer**, which has a max range of 32767.

This change will go live in next release.

**Comment by 9752354576** [comment]
Greate, salute to your efforts, i will test and let you know soon.

Thank you very much sir in advance.

//Pankaj.

**Comment by 9752354576** [comment]
Hello Pritesh,

Sorry i have not read last line i.e 'This change will go live in next
release'.
So please let me know next release date?

**Comment by Pritesh-Mhatre** [comment]
Tested successfully and released in latest version 3.2.1.

**Comment by Pritesh-Mhatre** [comment]
We missed to publish couple of files in the release, please re-run the setup we have re-uploaded it.

**Comment by 9752354576** [comment]
I tested both features it's working perfectly without any concerns.

Superb, thank you so much Pritish sir,
I appreciate your genuine efforts.

Once Again thank you so much.


//Pankaj

**Comment by 9752354576** [comment]
Hello Pritesh,

I have setup Auto Trader over google cloud, but it's working very slow over
cloud as compared to my laptop, so can we do something for this or do we
have any solution for this issue?


//Pankaj.

**Comment by 9752354576** [comment]
I have found solution, please don't invest your time in this.

// Pankaj.

**Comment by 9752354576** [comment]
Hello Predesh,

Earlier I have reported blow two bug/improvement, as per your offer I
supposed to benifited 15 day's free license but I have received that from
your side.

Please do the needful.
My current license will be expire on 24 March 2019.

Apart from this I want to open account in Alice Blue through your
reference, please let me know process.

//Pankaj
Contact : 9752354576.

**Comment by 9752354576** [comment]
Hello Pritesh,

I have opened trading account in Alice Blue through your referral link, as
per offer please provide me 1 one month extension of Auto Trader software.

My current paid license will be expire on 24 march 2019. My Alice client
is AB013385.

Please do the needful.


Thanks and Regards
Pankaj Solanki
Contact: 9752354576
