### ISSUE TITLE
Stale Price check should stop for scrips whose market has ended

### ISSUE THREAD

**Issue by Pritesh-Mhatre** [Pritesh-Mhatre/autotrader#61]
NSE scrips give error when market ends, but user is still trading in MCX

**Comment by shaikbau** [comment]
hi sir this bug is highlighted by me i hope my licence will be extended for 15days
Your unique id: e3504938-462c-46c7-8def-b4c0d81339b4
i sent this error thr my mail id shaik.babu1971@gmail.com to support mail
shaik babu 9441252624

**Comment by Pritesh-Mhatre** [comment]
Yes, we have extended your license.

**Comment by Pritesh-Mhatre** [comment]
> hi sir this bug is highlighted by me i hope my licence will be extended for 15days
> Your unique id: e3504938-462c-46c7-8def-b4c0d81339b4
> i sent this error thr my mail id [shaik.babu1971@gmail.com](mailto:shaik.babu1971@gmail.com) to support mail
> shaik babu 9441252624

Yes, we have extended your license.

**Comment by shaikbau** [comment]
THANK YOU SIR
*REGARDS.......*

*SHAIK BABU*
*                Development Officer,*
*LIC OF INDIA*
*Ashoknagar, MANUGURU*
*KHAMMAM*
*TELANGANA *
* 507117*


*shaik_babu@yahoo.co.in <shaik_babu@yahoo.co.in>*

*babu.shaik@licindia.com <babu.shaik@licindia.com>*



*9441 25 26 248497 93 7654*
