### ISSUE TITLE
restore defaults option for settings -- enhancement

### ISSUE THREAD

**Issue by shaikbau** [Pritesh-Mhatre/autotrader#63]
![screenshot 17](https://user-images.githubusercontent.com/46390245/52898088-b1bebe00-31ff-11e9-9282-c010b0482bc0.png)

sir we dont we add restore defaults option for settings in auto trader
 if user by mistake changes settings and wants to restore to defaults then it is very usefull

**Comment by shaikbau** [comment]
why dont we add resote default values option

**Comment by Pritesh-Mhatre** [comment]
There is already an issue open for this, and this is a low priority item as of now. Focus is not alice blue & nowonline.in

We will pick it up as soon as we have free time.

https://github.com/Pritesh-Mhatre/autotrader/issues/44
