### ISSUE TITLE
in rtd backfill option on the top it is easy for users 

### ISSUE THREAD

**Issue by shaikbau** [Pritesh-Mhatre/autotrader#64]
sir in rtd 
if back fill option is on the top
insted of going down and down to back fill option button
it is very easy if it is on the top also
ok to back fill latest script it is in the down
but to back fill all the scripts 
one more button on the top is easy for many users
it is enhancement
![screenshot 18](https://user-images.githubusercontent.com/46390245/52898194-e717db80-3200-11e9-9fbd-8cc0d5301dd7.png)

**Comment by Pritesh-Mhatre** [comment]
Accepted as a low priority enhancement.
