### ISSUE TITLE
pop up menu with all symbols in symbols 

### ISSUE THREAD

**Issue by shaikbau** [Pritesh-Mhatre/autotrader#65]
why dont we add popup menu at symbols place.... insted of empty 
![screenshot 20](https://user-images.githubusercontent.com/46390245/52898298-02371b00-3202-11e9-8cdf-6331b1c41be9.png)
text box
if add popup memu and populate all respective scripts it is very easy for a trader to choose
symbols 
and no errors will be displayed
i think it needs extra work for you to manage  symbols if any changes in scripts etc...

**Comment by Pritesh-Mhatre** [comment]
Thanks for the feedback, but it is not possible as the total scripts count is anywhere between 70 to 80 thousand. It will not fit into a pop-up.
